apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-parser-deployment
  labels:
    app: csv-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csv-parser
  template:
    metadata:
      labels:
        app: csv-parser
    spec:
      containers:
        - name: csv-parser
          image: localhost:5000/csv-parser
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: csv-parser-service
spec:
  selector:
    app: csv-parser
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
