apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: csv-parser
  name: csv-parser
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: csv-parser
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: csv-parser
    spec:
      containers:
        - image: csv-parser
          name: csv-parser
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: csv-parser
  name: csv-parser
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: csv-parser
status:
  loadBalancer: {}
